In [ ]:
# Lab 7 Learning rate and Evaluation
import tensorflow as tf

x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

# try different learning_rate
# learning_rate = 65535  # ? it works too hahaha
learning_rate = 0.1
# learning_rate = 1e-10  # small learning rate won't work either

tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=3, input_dim=3, activation='softmax'))
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.SGD(lr=learning_rate), metrics=['accuracy'])

tf.model.fit(x_data, y_data, epochs=1000)

# predict
print("Prediction: ", tf.model.predict_classes(x_test))

# Calculate the accuracy
print("Accuracy: ", tf.model.evaluate(x_test, y_test)[1])

In [7]:
import tensorflow as tf

x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

learning_rate = 0.1
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=3, input_dim=3, activation='softmax'))
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.SGD(lr=learning_rate), metrics=['accuracy'])

tf.model.summary()
tf.model.fit(x_data, y_data, epochs=1000)


print("Prediction : ", tf.model.predict_classes(x_test))
print("Accuracy : ", tf.model.evaluate(x_test,y_test)[1])

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_5 (Dense)             (None, 3)                 12        
                                                                 
Total params: 12
Trainable params: 12
Non-trainable params: 0
_________________________________________________________________
Epoch 1/1000
1/1 [==============================] - 0s 214ms/step - loss: 2.4939 - accuracy: 0.3750
Epoch 2/1000
1/1 [==============================] - 0s 3ms/step - loss: 1.0607 - accuracy: 0.3750
Epoch 3/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.9795 - accuracy: 0.5000
Epoch 4/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.9625 - accuracy: 0.5000
Epoch 5/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.9513 - accuracy: 0.6250
Epoch 6/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.9420 - accuracy: 0.5

1/1 [==============================] - 0s 4ms/step - loss: 0.7113 - accuracy: 0.7500
Epoch 79/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.7096 - accuracy: 0.7500
Epoch 80/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.7079 - accuracy: 0.7500
Epoch 81/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.7063 - accuracy: 0.7500
Epoch 82/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.7046 - accuracy: 0.7500
Epoch 83/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.7030 - accuracy: 0.7500
Epoch 84/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.7014 - accuracy: 0.7500
Epoch 85/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.6998 - accuracy: 0.7500
Epoch 86/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.6983 - accuracy: 0.7500
Epoch 87/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.6967 - accuracy: 0.7500
Epoch 88/1000
1/1 [=====

1/1 [==============================] - 0s 4ms/step - loss: 0.6144 - accuracy: 0.7500
Epoch 161/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.6135 - accuracy: 0.7500
Epoch 162/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.6127 - accuracy: 0.7500
Epoch 163/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.6119 - accuracy: 0.7500
Epoch 164/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.6111 - accuracy: 0.7500
Epoch 165/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.6102 - accuracy: 0.7500
Epoch 166/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.6094 - accuracy: 0.7500
Epoch 167/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.6086 - accuracy: 0.7500
Epoch 168/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.6078 - accuracy: 0.7500
Epoch 169/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.6070 - accuracy: 0.7500
Epoch 170/1000


1/1 [==============================] - 0s 3ms/step - loss: 0.5589 - accuracy: 0.8750
Epoch 243/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.5584 - accuracy: 0.8750
Epoch 244/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.5578 - accuracy: 0.8750
Epoch 245/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.5573 - accuracy: 0.8750
Epoch 246/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.5567 - accuracy: 0.8750
Epoch 247/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.5562 - accuracy: 0.8750
Epoch 248/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.5556 - accuracy: 0.8750
Epoch 249/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.5551 - accuracy: 0.8750
Epoch 250/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.5545 - accuracy: 0.8750
Epoch 251/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.5540 - accuracy: 0.8750
Epoch 252/1000


1/1 [==============================] - 0s 4ms/step - loss: 0.5197 - accuracy: 0.8750
Epoch 325/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.5192 - accuracy: 0.8750
Epoch 326/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.5188 - accuracy: 0.8750
Epoch 327/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.5184 - accuracy: 0.8750
Epoch 328/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.5180 - accuracy: 0.8750
Epoch 329/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.5176 - accuracy: 0.8750
Epoch 330/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.5172 - accuracy: 0.8750
Epoch 331/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.5168 - accuracy: 0.8750
Epoch 332/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.5163 - accuracy: 0.8750
Epoch 333/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.5159 - accuracy: 0.8750
Epoch 334/1000


1/1 [==============================] - 0s 3ms/step - loss: 0.4889 - accuracy: 0.8750
Epoch 407/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4886 - accuracy: 0.8750
Epoch 408/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4882 - accuracy: 0.8750
Epoch 409/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.4879 - accuracy: 0.8750
Epoch 410/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4876 - accuracy: 0.8750
Epoch 411/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4872 - accuracy: 0.8750
Epoch 412/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4869 - accuracy: 0.8750
Epoch 413/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.4866 - accuracy: 0.8750
Epoch 414/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4862 - accuracy: 0.8750
Epoch 415/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4859 - accuracy: 0.8750
Epoch 416/1000


1/1 [==============================] - 0s 3ms/step - loss: 0.4635 - accuracy: 1.0000
Epoch 489/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.4632 - accuracy: 1.0000
Epoch 490/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4629 - accuracy: 1.0000
Epoch 491/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4626 - accuracy: 1.0000
Epoch 492/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.4624 - accuracy: 1.0000
Epoch 493/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4621 - accuracy: 1.0000
Epoch 494/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.4618 - accuracy: 1.0000
Epoch 495/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4615 - accuracy: 1.0000
Epoch 496/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.4612 - accuracy: 1.0000
Epoch 497/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.4610 - accuracy: 1.0000
Epoch 498/1000


1/1 [==============================] - 0s 4ms/step - loss: 0.4418 - accuracy: 1.0000
Epoch 571/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4416 - accuracy: 1.0000
Epoch 572/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.4414 - accuracy: 1.0000
Epoch 573/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.4411 - accuracy: 1.0000
Epoch 574/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.4409 - accuracy: 1.0000
Epoch 575/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4406 - accuracy: 1.0000
Epoch 576/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4404 - accuracy: 1.0000
Epoch 577/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.4401 - accuracy: 1.0000
Epoch 578/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4399 - accuracy: 1.0000
Epoch 579/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4396 - accuracy: 1.0000
Epoch 580/1000


1/1 [==============================] - 0s 4ms/step - loss: 0.4230 - accuracy: 1.0000
Epoch 653/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.4228 - accuracy: 1.0000
Epoch 654/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4226 - accuracy: 1.0000
Epoch 655/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4223 - accuracy: 1.0000
Epoch 656/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.4221 - accuracy: 1.0000
Epoch 657/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.4219 - accuracy: 1.0000
Epoch 658/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4217 - accuracy: 1.0000
Epoch 659/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4215 - accuracy: 1.0000
Epoch 660/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4213 - accuracy: 1.0000
Epoch 661/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4211 - accuracy: 1.0000
Epoch 662/1000


1/1 [==============================] - 0s 3ms/step - loss: 0.4064 - accuracy: 1.0000
Epoch 735/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4062 - accuracy: 1.0000
Epoch 736/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.4060 - accuracy: 1.0000
Epoch 737/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4058 - accuracy: 1.0000
Epoch 738/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.4056 - accuracy: 1.0000
Epoch 739/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4054 - accuracy: 1.0000
Epoch 740/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4052 - accuracy: 1.0000
Epoch 741/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4050 - accuracy: 1.0000
Epoch 742/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.4048 - accuracy: 1.0000
Epoch 743/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.4046 - accuracy: 1.0000
Epoch 744/1000


1/1 [==============================] - 0s 3ms/step - loss: 0.3915 - accuracy: 1.0000
Epoch 817/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.3913 - accuracy: 1.0000
Epoch 818/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.3911 - accuracy: 1.0000
Epoch 819/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3910 - accuracy: 1.0000
Epoch 820/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3908 - accuracy: 1.0000
Epoch 821/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.3906 - accuracy: 1.0000
Epoch 822/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3905 - accuracy: 1.0000
Epoch 823/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.3903 - accuracy: 1.0000
Epoch 824/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3901 - accuracy: 1.0000
Epoch 825/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3900 - accuracy: 1.0000
Epoch 826/1000


1/1 [==============================] - 0s 3ms/step - loss: 0.3781 - accuracy: 1.0000
Epoch 899/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.3780 - accuracy: 1.0000
Epoch 900/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.3778 - accuracy: 1.0000
Epoch 901/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.3776 - accuracy: 1.0000
Epoch 902/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3775 - accuracy: 1.0000
Epoch 903/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3773 - accuracy: 1.0000
Epoch 904/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3772 - accuracy: 1.0000
Epoch 905/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3770 - accuracy: 1.0000
Epoch 906/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3769 - accuracy: 1.0000
Epoch 907/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3767 - accuracy: 1.0000
Epoch 908/1000


1/1 [==============================] - 0s 4ms/step - loss: 0.3660 - accuracy: 1.0000
Epoch 981/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3658 - accuracy: 1.0000
Epoch 982/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.3657 - accuracy: 1.0000
Epoch 983/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3655 - accuracy: 1.0000
Epoch 984/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3654 - accuracy: 1.0000
Epoch 985/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.3652 - accuracy: 1.0000
Epoch 986/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.3651 - accuracy: 1.0000
Epoch 987/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3650 - accuracy: 1.0000
Epoch 988/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.3648 - accuracy: 1.0000
Epoch 989/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.3647 - accuracy: 1.0000
Epoch 990/1000


In [5]:
#non-normalized
import tensorflow as tf
import numpy as np

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=1, input_dim=4))
tf.model.add(tf.keras.layers.Activation('linear'))
tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=1e-5))
tf.model.summary()

history = tf.model.fit(x_data, y_data, epochs=100)

print(history.history['loss']) # loss == nan

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 1)                 5         
                                                                 
 activation (Activation)     (None, 1)                 0         
                                                                 
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
1/1 [==============================] - 0s 170ms/step - loss: 172695207936.0000
Epoch 2/100
1/1 [==============================] - 0s 3ms/step - loss: 189736808521982870707765248.0000
Epoch 3/100
1/1 [==============================] - 0s 3ms/step - loss: inf
Epoch 4/100
1/1 [==============================] - 0s 3ms/step - loss: inf
Epoch 5/100
1/1 [==============================] - 0s 3ms/step - loss: inf
Epoch 6/100
1/1 [===================

1/1 [==============================] - 0s 4ms/step - loss: nan
Epoch 100/100
1/1 [==============================] - 0s 2ms/step - loss: nan
[172695207936.0, 1.8973680852198287e+26, inf, inf, inf, inf, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]


In [8]:
#normalized(min_max_scaler)
import tensorflow as tf
import numpy as np


def min_max_scaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)


xy = np.array(
    [
        [828.659973, 833.450012, 908100, 828.349976, 831.659973],
        [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
        [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
        [816, 820.958984, 1008100, 815.48999, 819.23999],
        [819.359985, 823, 1188100, 818.469971, 818.97998],
        [819, 823, 1198100, 816, 820.450012],
        [811.700012, 815.25, 1098100, 809.780029, 813.669983],
        [809.51001, 816.659973, 1398100, 804.539978, 809.559998],
    ]
)

# very important. It does not work without it.
xy = min_max_scaler(xy)
print(xy)

'''
[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]
'''

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=1, input_dim=4))
tf.model.add(tf.keras.layers.Activation('linear'))
tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=1e-5))
tf.model.summary()

history = tf.model.fit(x_data, y_data, epochs=1000)

predictions = tf.model.predict(x_data)
score = tf.model.evaluate(x_data, y_data)

print('Prediction: \n', predictions)
print('Cost: ', score)

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]
Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 1)                 5         
                                                                 
 activation_1 (Activation)   (None, 1)                 0         
                                                                 
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________

1/1 [==============================] - 0s 2ms/step - loss: 0.1314
Epoch 90/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1314
Epoch 91/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1314
Epoch 92/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1313
Epoch 93/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1313
Epoch 94/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1313
Epoch 95/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1313
Epoch 96/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1313
Epoch 97/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1313
Epoch 98/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1313
Epoch 99/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1313
Epoch 100/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1313
Epoch 101/1000
1/1 [==============================] -

1/1 [==============================] - 0s 2ms/step - loss: 0.1305
Epoch 191/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1305
Epoch 192/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1304
Epoch 193/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1304
Epoch 194/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1304
Epoch 195/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1304
Epoch 196/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1304
Epoch 197/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1304
Epoch 198/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1304
Epoch 199/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1304
Epoch 200/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1304
Epoch 201/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1304
Epoch 202/1000
1/1 [=======================

1/1 [==============================] - 0s 2ms/step - loss: 0.1296
Epoch 292/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1296
Epoch 293/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1295
Epoch 294/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1295
Epoch 295/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1295
Epoch 296/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1295
Epoch 297/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1295
Epoch 298/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1295
Epoch 299/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1295
Epoch 300/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1295
Epoch 301/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1295
Epoch 302/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1295
Epoch 303/1000
1/1 [=======================

1/1 [==============================] - 0s 3ms/step - loss: 0.1287
Epoch 393/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1287
Epoch 394/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1287
Epoch 395/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1286
Epoch 396/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1286
Epoch 397/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1286
Epoch 398/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1286
Epoch 399/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1286
Epoch 400/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1286
Epoch 401/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1286
Epoch 402/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1286
Epoch 403/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1286
Epoch 404/1000
1/1 [=======================

1/1 [==============================] - 0s 3ms/step - loss: 0.1278
Epoch 494/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1278
Epoch 495/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1278
Epoch 496/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1278
Epoch 497/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1278
Epoch 498/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1277
Epoch 499/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1277
Epoch 500/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1277
Epoch 501/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1277
Epoch 502/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1277
Epoch 503/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1277
Epoch 504/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1277
Epoch 505/1000
1/1 [=======================

1/1 [==============================] - 0s 3ms/step - loss: 0.1269
Epoch 595/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1269
Epoch 596/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1269
Epoch 597/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1269
Epoch 598/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1269
Epoch 599/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1269
Epoch 600/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1269
Epoch 601/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1269
Epoch 602/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1268
Epoch 603/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1268
Epoch 604/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.1268
Epoch 605/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1268
Epoch 606/1000
1/1 [=======================

1/1 [==============================] - 0s 2ms/step - loss: 0.1260
Epoch 696/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1260
Epoch 697/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1260
Epoch 698/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1260
Epoch 699/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1260
Epoch 700/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1260
Epoch 701/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1260
Epoch 702/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1260
Epoch 703/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1260
Epoch 704/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1260
Epoch 705/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1260
Epoch 706/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1259
Epoch 707/1000
1/1 [=======================

1/1 [==============================] - 0s 2ms/step - loss: 0.1252
Epoch 797/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1252
Epoch 798/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1252
Epoch 799/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1252
Epoch 800/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1251
Epoch 801/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1251
Epoch 802/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1251
Epoch 803/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1251
Epoch 804/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1251
Epoch 805/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1251
Epoch 806/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1251
Epoch 807/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1251
Epoch 808/1000
1/1 [=======================

1/1 [==============================] - 0s 2ms/step - loss: 0.1243
Epoch 898/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1243
Epoch 899/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1243
Epoch 900/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1243
Epoch 901/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1243
Epoch 902/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1243
Epoch 903/1000
1/1 [==============================] - 0s 999us/step - loss: 0.1243
Epoch 904/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1243
Epoch 905/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1243
Epoch 906/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1242
Epoch 907/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.1242
Epoch 908/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1242
Epoch 909/1000
1/1 [=====================

1/1 [==============================] - 0s 2ms/step - loss: 0.1235
Epoch 999/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.1235
Epoch 1000/1000
1/1 [==============================] - 0s 51ms/step - loss: 0.1234
Prediction: 
 [[ 0.4444787 ]
 [ 0.26428849]
 [ 0.24478236]
 [ 0.21660368]
 [ 0.25039542]
 [ 0.19355713]
 [ 0.09972657]
 [-0.02184826]]
Cost:  0.12344444543123245
