In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
torch.manual_seed(1)

x_train = torch.FloatTensor([[73, 80, 75],
                            [93, 88, 93],
                            [89, 91, 90],
                            [96, 98, 100],
                            [73, 66, 70]])
y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

model = nn.Linear(3,1)
print(list(model.parameters()))
optimizer = optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 2000
for epoch in range(nb_epochs + 1):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch%100==0 :
        print('Epoch:{:4d}/{} Cost:{:.6f}'.format(epoch, nb_epochs, cost.item()))
        
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]
Epoch:   0/2000 Cost:31667.599609
Epoch: 100/2000 Cost:0.225993
Epoch: 200/2000 Cost:0.223911
Epoch: 300/2000 Cost:0.221941
Epoch: 400/2000 Cost:0.220059
Epoch: 500/2000 Cost:0.218271
Epoch: 600/2000 Cost:0.216575
Epoch: 700/2000 Cost:0.214950
Epoch: 800/2000 Cost:0.213413
Epoch: 900/2000 Cost:0.211952
Epoch:1000/2000 Cost:0.210559
Epoch:1100/2000 Cost:0.209230
Epoch:1200/2000 Cost:0.207967
Epoch:1300/2000 Cost:0.206762
Epoch:1400/2000 Cost:0.205618
Epoch:1500/2000 Cost:0.204529
Epoch:1600/2000 Cost:0.203481
Epoch:1700/2000 Cost:0.202486
Epoch:1800/2000 Cost:0.201539
Epoch:1900/2000 Cost:0.200634
Epoch:2000/2000 Cost:0.199770
[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]


In [2]:
# nn.Module의 클래스 구현
import torch
import torch.nn as nn
import torch.optim as optim

class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3,1)
        
    def forward(self,x):
        return self.linear(x)

x_train = torch.FloatTensor([[73, 80, 75],
                            [93, 88, 93],
                            [89, 91, 90],
                            [96, 98, 100],
                            [73, 66, 70]])
y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

model = LinearRegressionModel()
print(list(model.parameters()))
optimizer = optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 2000
for epoch in range(nb_epochs + 1):
    prediction = model.forward(x_train)
    cost = F.mse_loss(prediction, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch%100==0 :
        print('Epoch:{:4d}/{} Cost:{:.6f}'.format(epoch, nb_epochs, cost.item()))
        
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.5435,  0.3462, -0.1188]], requires_grad=True), Parameter containing:
tensor([0.2937], requires_grad=True)]
Epoch:   0/2000 Cost:39633.414062
Epoch: 100/2000 Cost:11.480746
Epoch: 200/2000 Cost:10.894592
Epoch: 300/2000 Cost:10.339335
Epoch: 400/2000 Cost:9.813351
Epoch: 500/2000 Cost:9.315010
Epoch: 600/2000 Cost:8.842962
Epoch: 700/2000 Cost:8.395753
Epoch: 800/2000 Cost:7.972028
Epoch: 900/2000 Cost:7.570637
Epoch:1000/2000 Cost:7.190376
Epoch:1100/2000 Cost:6.830142
Epoch:1200/2000 Cost:6.488811
Epoch:1300/2000 Cost:6.165472
Epoch:1400/2000 Cost:5.859105
Epoch:1500/2000 Cost:5.568909
Epoch:1600/2000 Cost:5.293931
Epoch:1700/2000 Cost:5.033408
Epoch:1800/2000 Cost:4.786575
Epoch:1900/2000 Cost:4.552718
Epoch:2000/2000 Cost:4.331151
[Parameter containing:
tensor([[0.4789, 0.8222, 0.7059]], requires_grad=True), Parameter containing:
tensor([0.3070], requires_grad=True)]


In [6]:
# dataset, dataloader (batch를 나눠서 하기 위해 사용하는듯)
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

x_train = torch.FloatTensor([[73, 80, 75],
                            [93, 88, 93],
                            [89, 91, 90],
                            [96, 98, 100],
                            [73, 66, 70]])
y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

dataset = TensorDataset(x_train, y_train)
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

model = nn.Linear(3,1)
optimizer=optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
    for batch_idx, samples in enumerate(dataloader):
        print(batch_idx)
        print(samples)
        x_train, y_train = samples
        prediction = model(x_train)
        cost = F.mse_loss(prediction, y_train)
        
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()
        
        print('Epoch:{:2d}/{} Batch:{}/{} Cost:{:.6f}'.format(epoch, nb_epochs, batch_idx+1, len(dataloader), cost.item()))

0
[tensor([[93., 88., 93.],
        [89., 91., 90.]]), tensor([[185.],
        [180.]])]
Epoch: 0/20 Batch:1/3 Cost:8862.895508
1
[tensor([[73., 80., 75.],
        [73., 66., 70.]]), tensor([[152.],
        [142.]])]
Epoch: 0/20 Batch:2/3 Cost:1461.758545
2
[tensor([[ 96.,  98., 100.]]), tensor([[196.]])]
Epoch: 0/20 Batch:3/3 Cost:1149.987671
0
[tensor([[ 96.,  98., 100.],
        [ 93.,  88.,  93.]]), tensor([[196.],
        [185.]])]
Epoch: 1/20 Batch:1/3 Cost:235.571991
1
[tensor([[73., 66., 70.],
        [89., 91., 90.]]), tensor([[142.],
        [180.]])]
Epoch: 1/20 Batch:2/3 Cost:37.515854
2
[tensor([[73., 80., 75.]]), tensor([[152.]])]
Epoch: 1/20 Batch:3/3 Cost:1.261714
0
[tensor([[ 96.,  98., 100.],
        [ 73.,  66.,  70.]]), tensor([[196.],
        [142.]])]
Epoch: 2/20 Batch:1/3 Cost:15.263241
1
[tensor([[93., 88., 93.],
        [73., 80., 75.]]), tensor([[185.],
        [152.]])]
Epoch: 2/20 Batch:2/3 Cost:6.956800
2
[tensor([[89., 91., 90.]]), tensor([[180.]])]
Epoch:

In [8]:
# Logistic regression
import torch
import torch.optim as optim

x_train = torch.FloatTensor([[1,2], [2,3], [3,1], [4,3], [5,3], [6,2]])
y_train = torch.FloatTensor([[0], [0], [0], [1], [1], [1]])

W = torch.zeros((2,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W,b], lr=1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):
    hypothesis = torch.sigmoid(x_train.matmul(W) + b)
    cost = -(y_train*torch.log(hypothesis) + (1 - y_train)*torch.log(1 - hypothesis)).mean()
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch%100==0 : 
        print('Epoch:{:4d}/{} Cost:{:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch:   0/1000 Cost:0.693147
Epoch: 100/1000 Cost:0.134722
Epoch: 200/1000 Cost:0.080643
Epoch: 300/1000 Cost:0.057900
Epoch: 400/1000 Cost:0.045300
Epoch: 500/1000 Cost:0.037261
Epoch: 600/1000 Cost:0.031673
Epoch: 700/1000 Cost:0.027556
Epoch: 800/1000 Cost:0.024394
Epoch: 900/1000 Cost:0.021888
Epoch:1000/1000 Cost:0.019852


In [14]:
# Logistic regression by nn.Module
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

x_train = torch.FloatTensor([[1,2], [2,3], [3,1], [4,3], [5,3], [6,2]])
y_train = torch.FloatTensor([[0], [0], [0], [1], [1], [1]])

model = nn.Sequential(nn.Linear(2,1), nn.Sigmoid())

optimizer = optim.SGD(model.parameters(), lr=1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):
    predicted_y = model(x_train)
    cost = F.binary_cross_entropy(predicted_y, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch%10==0:
        prediction = predicted_y >= torch.FloatTensor([0.5])
        correct_prediction = prediction.float() == y_train
        accuracy = correct_prediction.sum().item() / len(correct_prediction)
        print('Epoch:{:4d}/{} Cost:{:.6f} Accuracy:{:2.2f}%'.format(epoch, nb_epochs, cost.item(), accuracy*100))

Epoch:   0/1000 Cost:0.994583 Accuracy:50.00%
Epoch:  10/1000 Cost:0.411348 Accuracy:66.67%
Epoch:  20/1000 Cost:0.430951 Accuracy:83.33%
Epoch:  30/1000 Cost:0.360431 Accuracy:83.33%
Epoch:  40/1000 Cost:0.305088 Accuracy:83.33%
Epoch:  50/1000 Cost:0.255869 Accuracy:83.33%
Epoch:  60/1000 Cost:0.211406 Accuracy:100.00%
Epoch:  70/1000 Cost:0.175426 Accuracy:100.00%
Epoch:  80/1000 Cost:0.153818 Accuracy:100.00%
Epoch:  90/1000 Cost:0.141830 Accuracy:100.00%
Epoch: 100/1000 Cost:0.132340 Accuracy:100.00%
Epoch: 110/1000 Cost:0.124077 Accuracy:100.00%
Epoch: 120/1000 Cost:0.116803 Accuracy:100.00%
Epoch: 130/1000 Cost:0.110351 Accuracy:100.00%
Epoch: 140/1000 Cost:0.104589 Accuracy:100.00%
Epoch: 150/1000 Cost:0.099411 Accuracy:100.00%
Epoch: 160/1000 Cost:0.094734 Accuracy:100.00%
Epoch: 170/1000 Cost:0.090487 Accuracy:100.00%
Epoch: 180/1000 Cost:0.086613 Accuracy:100.00%
Epoch: 190/1000 Cost:0.083066 Accuracy:100.00%
Epoch: 200/1000 Cost:0.079805 Accuracy:100.00%
Epoch: 210/1000 Cos